#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo ""
  echo "Usage:"
  echo ""
  echo "./scripts/generate-module.sh products"
  echo ""
  exit 1
fi

MODULE=$1
MODULE_TITLE="$(tr '[:lower:]' '[:upper:]' <<< ${MODULE:0:1})${MODULE:1}"

echo "Generating module: $MODULE"

##############################################################################
# Directories
##############################################################################

mkdir -p app/'(dashboard)'/$MODULE
mkdir -p modules/$MODULE
mkdir -p services/$MODULE
mkdir -p types

##############################################################################
# Page
##############################################################################

cat > app/'(dashboard)'/$MODULE/page.tsx <<PAGE
import Breadcrumb from "@/components/common/breadcrumb";
import SectionCard from "@/components/common/section-card";
import ResourceHeader from "@/components/resource/resource-header";
import ResourceFilters from "@/components/resource/resource-filters";
import EmptyState from "@/components/common/empty-state";

export default function ${MODULE_TITLE}Page() {
  return (
    <>
      <Breadcrumb items={["$MODULE_TITLE"]} />

      <ResourceHeader
        title="$MODULE_TITLE"
        description="Manage all $MODULE"
        addLabel="$MODULE_TITLE"
      />

      <ResourceFilters />

      <SectionCard title="$MODULE_TITLE List">
        <EmptyState
          title="No $MODULE_TITLE Found"
          description="Create your first $MODULE_TITLE."
        />
      </SectionCard>
    </>
  );
}
PAGE

##############################################################################
# Service
##############################################################################

cat > services/$MODULE/$MODULE.service.ts <<SERVICE
export async function get${MODULE_TITLE}() {
  return [];
}
SERVICE

##############################################################################
# Types
##############################################################################

cat > types/$MODULE.ts <<TYPE
export interface ${MODULE_TITLE} {
  id: string;
}
TYPE

##############################################################################
# Module README
##############################################################################

cat > modules/$MODULE/README.md <<README
# $MODULE_TITLE Module

Generated by Healthila Module Generator.
README

echo ""
echo "======================================"
echo " Module '$MODULE' generated"
echo "======================================"
